### ISSUE TITLE
Uncorrect `animateToIndex` animation

### ISSUE THREAD

**Issue by krida2000** [robert-luoqing/flutter_list_view#21]
If call `animateToIndex` to element in end of the list, then animation will be uncorrect.

<details>
  <summary>Problem</summary>
  
  https://user-images.githubusercontent.com/71345244/209559725-76ba3cbf-fff7-4798-9b6d-50dfbae38655.mp4
</details>

I have fixed it by folowing changes:

<details>
  <summary>Fix</summary>
  
  ![image](https://user-images.githubusercontent.com/71345244/209559773-2a9fedcb-7aed-489d-8002-ead890a65e62.png)
</details>

**Comment by robert-luoqing** [comment]
Thanks @krida2000,  Could you please uncomment the line and test it to check whether is working fine?
```
jumpToIndex(index, offset, basedOnBottom);
```

The "jumpToIndex(index, offset, basedOnBottom);" is used to guarantee jump to correct position. The scrollOffset in position?.animateTo may not accurracy. bacause we didn't know the further item's height. So the jumpToIndex can ensure jump to correct position.

In this time, jumpToIndex is very important to ensure correct position the list view jump to finally.

**Comment by robert-luoqing** [comment]
BTW, Could you please show me the animateToIndex you have wrote? include its parameters.

Thanks,

**Comment by krida2000** [comment]
@robert-luoqing In screen all changes that I made.

If uncoment `jumpToIndex(index, offset, basedOnBottom);`, animation still be uncorrect. I think similar changes should be added to the `_handleJump` function to fix animation.
