### ISSUE TITLE
When the list item is Dismissible, scrolling will report an exception

### ISSUE THREAD

**Issue by qiangjindong** [robert-luoqing/flutter_list_view#25]
flutter: type 'Null' is not a subtype of type 'RenderBox' in type cast, #0      FlutterListViewRender.paint (package:flutter_list_view/src/flutter_list_view_render.dart:682:60)
flutter: #1      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
flutter: #2      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
flutter: #3      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:690:17)
flutter: #4      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:472:12)
flutter: #5      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:532:7)
flutter: #6      RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:665:38)
flutter: #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
flutter: #8      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
flutter: #9      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
flutter: #10     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
flutter: #11     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
flutter: #12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
flutter: #13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
flutter: #14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
flutter: #15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
flutter: #16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
flutter: #17     _rootRun (dart:async/zone.dart:1399:13)
flutter: #18     _CustomZone.run (dart:async/zone.dart:1301:19)
flutter: #19     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
flutter: #20     _invoke (dart:ui/hooks.dart:172:10)
flutter: #21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
flutter: #22     _drawFrame (dart:ui/hooks.dart:140:31)

**Comment by robert-luoqing** [comment]
Fixed, please update to flutter_list_view: ^1.1.22

**Comment by qiangjindong** [comment]
Thanks!
