### ISSUE TITLE
How to do pagination with this package ?

### ISSUE THREAD

**Issue by nergal79** [robert-luoqing/flutter_list_view#33]
We have a need of pagination in vertical list view .  2-way actually both top and bottom ..
How this can be achieved ? I don't see any scroll change listener in the code like Google's ListView package has ..

**Comment by robert-luoqing** [comment]
Please refer https://github.com/robert-luoqing/flutter_list_view/blob/master/example/lib/pull_to_refresh_list.dart. It integrates with pull_to_refresh to implement pagination

**Comment by nergal79** [comment]
@robert-luoqing  that's not I meant by pagination .. I need to make next page page once list is at bottom/top.

Anyways I found the answer. I am using the code below . and it works fine.. 

     `listViewController.sliverController.onPaintItemPositionsCallback =
        (double widgetHeight, List<FlutterListViewItemPosition> positions) {
      var firstVisiblePosition = positions.first;
      var lastVisiblePosition = positions.last;
      // here we can build logic around above position to call the next/prev page 
      
    };`   

Thanks for this amazing package man ...
